name: Build and push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  temporal:
    runs-on: self-hosted
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3

      - run: |
          docker build -f ./Dockerfile \
          -t satont/twir-temporal:latest \
          --cache-from type=gha,scope=twir-temporal \
          --cache-to type=gha,mode=max,scope=twir-temporal .

          docker push satont/twir-temporal:latest